### ISSUE TITLE
Week 0: Standard Types

### ISSUE THREAD

**Issue by gsamokovarov** [svetlik/Core-Ruby-1#1]
Като цяло ми харесват решенията ти. Проблемите, които имаш са дребни.

Малко проблеми при форматирането, които може да решиш като пуснеш rubocop. Като цяло избягвай експлицитен `then` в `if`.

Това също, бих го счел като форматираща грешка, но някой оператори ти връщат истина или лъжа, няма смисъл да го проверяваш отново. Вкарва шум в кода. Примерът е:

``` ruby
def anagram?(word, other)
  histogram(word) == histogram(other) ? true : false
end
```

Имаш грешка в решението на `remove_prefix`, защото не проверяваш дали префикса наистина съществува. Може да си напишеш тест, в които се опитваш да премахнеш префикс, който не се среща в текста.

**Comment by gsamokovarov** [comment]
Още така, имаш коментиран код в git. Като цяло, това го считаме като [code smell](http://en.wikipedia.org/wiki/Code_smell). Особено ако си истрил код, който вече е бил къмитнат в гит. Тогава, ако ти трябва кода, винаги може да си го вземеш. Няма смисъл да седи и да цапа :)

**Comment by svetlik** [comment]
Благодаря!
Според rubocop форматирането изглежда добре вече :)
За експлицитния then - разбрано; нещо, което впоследствие научих, но за което в началото не съм внимавал.
Някой ден, може би, ще се случи чудо и ще успея да разбера кога всъщност е най-удачно да ползвам тернарен оператор; засега мисля да бягам надалеч от него :)
Добавих проверки за remove_prefix и за remove_suffix в методите. Съответно, и тестове. 
За тестовете, ок ли е да проверявам дали при незадоволително подаден префикс/суфикс, получавам nil? Или е по-добре да хвана хвърления error?
